name: Generate GitHub Stats
on:
  schedule:
    - cron: "0 */12 * * *"   # 12시간마다 갱신
  workflow_dispatch: {}       # 수동 실행 버튼
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jstrieb/github-stats@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "update stats" || echo "no changes"
          git push
